// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvCNexyQR5zXeLnw5TxE3di4oKIghwQCc',
    appId: '1:757764865979:web:8da09a0e344f1745ab0e9e',
    messagingSenderId: '757764865979',
    projectId: 'blog-platform-app',
    authDomain: 'blog-platform-app.firebaseapp.com',
    storageBucket: 'blog-platform-app.appspot.com',
    measurementId: 'G-QQET0Y9HQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs7v8iMDCiKhkS3JUwIDbxlYHboFYVPWc',
    appId: '1:757764865979:android:6555a4b7d379ab80ab0e9e',
    messagingSenderId: '757764865979',
    projectId: 'blog-platform-app',
    storageBucket: 'blog-platform-app.appspot.com',
  );
}
